from Tkinter import *
from tkMessageBox import *
import sqlite3
con=sqlite3.Connection('hrdb')
cur=con.cursor()
root=Tk()
root.geometry('1020x468')
a=PhotoImage(file="sbi.gif")
l=Label(root,image=a)
l.grid(row=0,column=0,columnspan=4,sticky=W)
root.title("BANK MANAGEMENT SYSTEM")
root.configure(bg='Midnight Blue')
#########################################################create account#######################################################################################################
def create():
    root1=Tk()
    root1.configure(bg='Lavender')
    cur.execute('create table if not exists detail(e varchar(20),f varchar(30),g date,h varchar(60),i varchar(20),j number,k varchar(40),l number PRIMARY KEY,n number,o number,p varchar(30),q number,r date)')
    root1.title("Bank management system")
    Label(root1,text='Add new Account',font=' times 20 bold italic',fg='Red',bg='Lavender').grid(row=0,column=1)
    Label(root1,text='Consumer Details',font='Arial 10 bold',relief='ridge',bg='Lavender').grid(row=1,column=1,columnspan=2)
    Label(root1,text='Name',font='times 13',bg='Lavender').grid(row=2,column=1)
    e=Entry(root1,font='times 10 bold',bd=3)
    e.grid(row=2,column=2)
    Label(root1,text='Father name',font='times 13',bg='Lavender').grid(row=3,column=1)
    f=Entry(root1,font='times 10 bold',bd=3)
    f.grid(row=3,column=2)
    Label(root1,text='Date of birth',font='times 13',bg='Lavender').grid(row=4,column=1)
    g=Entry(root1,font='times 10 bold',bd=3)
    g.grid(row=4,column=2)
    Label(root1,text='Address',font='times 13',bg='Lavender').grid(row=5,column=1)
    h=Entry(root1,font='times 10 bold',bd=3)
    h.grid(row=5,column=2)
    Label(root1,text='Gender',font='times 13',bg='Lavender').grid(row=6,column=1)
    i=Entry(root1,font='times 10 bold',bd=3)
    i.grid(row=6,column=2)
    Label(root1,text='Mobile number',font='times 13',bg='Lavender').grid(row=7,column=1)
    j=Entry(root1,font='times 10 bold',bd=3)
    j.grid(row=7,column=2)
    Label(root1,text='Aadhar card',font='times 13',bg='Lavender').grid(row=8,column=1)
    k=Entry(root1,font='times 10 bold',bd=3)
    k.grid(row=8,column=2)
    Label(root1,text='Enter account number',font='times 10 bold',bg='Lavender').grid(row=0,column=3)
    l=Entry(root1,font='times 10 bold',bd=3)
    l.grid(row=0,column=4)
    Label(root1,text='Account details',font='Arial 10 bold',relief='ridge',bg='Lavender').grid(row=1,column=3)
    Label(root1,text='Balance',font='times 13',bg='Lavender').grid(row=2,column=3)
    n=Entry(root1,font='times 10 bold',bd=3)
    n.grid(row=2,column=4)
    Label(root1,text='Pin no',font='times 13',bg='Lavender').grid(row=3,column=3)
    o=Entry(root1,font='times 10 bold',bd=3)
    o.grid(row=3,column=4)
    Label(root1,text='Nomination',font='times 13',bg='Lavender').grid(row=4,column=3)
    p=Entry(root1,font='times 10 bold',bd=3)
    p.grid(row=4,column=4)
    Label(root1,text='Card no.',font='times 13',bg='Lavender').grid(row=5,column=3)
    q=Entry(root1,font='times 10 bold',bd=3)
    q.grid(row=5,column=4)
    Label(root1,text='date of joining',font='times 13',bg='Lavender').grid(row=6,column=3)
    r=Entry(root1,font='times 10 bold',bd=3)
    r.grid(row=6,column=4)
    def insert():
       try:
           cur.execute('insert into detail values(?,?,?,?,?,?,?,?,?,?,?,?,?)',(e.get(),f.get(),g.get(),h.get(),i.get(),j.get(),k.get(),l.get(),n.get(),o.get(),p.get(),q.get(),r.get()))
           con.commit()
           x=askyesnocancel('select an option','create account for sure?')
           if(x==TRUE):
                showinfo('Message','account created successfully')
        
           if(x==FALSE):
                showinfo('message','account not created')
       except:
           
           if(l==l.get()):
               showerror('error','account already exists')        
    Button(root1,text='Create',font='times 10 bold',width=10,height=2,bd=5,command=insert).grid(row=8,column=3)
    Button(root1,text='Back',font='times 10 bold',width=10,height=2,bd=5,command=root1.destroy).grid(row=8,column=4)
Button(root,text='Create new account',font='times 10 bold',width=20,height=1,bd=6,command=create).grid(row=2,column=0)
######################################################credit account###############################################################################################
def credit():
    root2=Toplevel()
    root2.configure(bg='Lavender')
    root2.title("Bank management system")
    Label(root2,text='Enter account number',font='times 15 bold',bg='Lavender').grid(row=0,column=0)
    l=Entry(root2,font='times 15 bold',bd=3)
    l.grid(row=0,column=1)
    Label(root2,text='Enter amount to be credited',font='times 15 bold',bg='Lavender').grid(row=4,column=0)
    s=Entry(root2,font='times 15 bold',bd=3)
    s.grid(row=4,column=1,pady=20)
    def modify():
        k=int(l.get())
        cur.execute('select n from detail where detail.l=(?)',(k,))
        x=cur.fetchall()
        x=x[0][0]
        v=int(s.get())
        y=int(x)+int(s.get())
        cur.execute('UPDATE detail SET n=? WHERE l=?',(y,k))
        con.commit() 
        showinfo('ok','account credited')
         
    def show():
        k=l.get()
        cur.execute('select * from detail where detail.l=?',(k,))
        ans=cur.fetchall()
        con.commit()
        for i in ans:
            root5=Tk()
            root5.title("Bank management system")
            Label(root5,text='Credit Cash To Account',font='times 20 bold italic',fg='red',bg='Lavender').grid(row=0,column=1)
            Label(root5,text='Consumer Details',font='times 10 bold',relief='ridge',bg='Lavender').grid(row=1,column=1,columnspan=2)
            Label(root5,text='Name',font='times 13',bg='Lavender').grid(row=2,column=1)
            name=Entry(root5,font='times 10 bold',bd=3)
            name.insert(0,i[0])
            name.grid(row=2,column=2)
            Label(root5,text='Father name',font='times 13',bg='Lavender').grid(row=3,column=1)
            fname=Entry(root5,font='times 10 bold',bd=3)
            fname.insert(0,i[1])
            fname.grid(row=3,column=2)
            Label(root5,text='Date of birth',font='times 13',bg='Lavender').grid(row=4,column=1)
            dob=Entry(root5,font='times 10 bold',bd=3)
            dob.insert(0,i[2])
            dob.grid(row=4,column=2)
            Label(root5,text='Address',font='times 13',bg='Lavender').grid(row=5,column=1)
            address=Entry(root5,font='times 10 bold',bd=3)
            address.insert(0,i[3])
            address.grid(row=5,column=2)
            Label(root5,text='Gender',font='times 13',bg='Lavender').grid(row=6,column=1)
            gender=Entry(root5,font='times 10 bold',bd=3)
            gender.insert(0,i[4])
            gender.grid(row=6,column=2)
            Label(root5,text='Mobile number',font='times 13',bg='Lavender').grid(row=7,column=1)
            mobno=Entry(root5,font='times 10 bold',bd=3)
            mobno.insert(0,i[5])
            mobno.grid(row=7,column=2)
            Label(root5,text='Aadhar card',font='times 13',bg='Lavender').grid(row=8,column=1)
            aadhar=Entry(root5,font='times 10 bold',bd=3)
            aadhar.insert(0,i[6])
            aadhar.grid(row=8,column=2)
            Label(root5,text='Enter account number',font='times 10 bold',bg='Lavender').grid(row=0,column=3)
            accno=Entry(root5,font='times 10 bold',bd=3)
            accno.insert(0,i[7])
            accno.grid(row=0,column=4)
            Label(root5,text='Account details',font='times 10 bold',relief='ridge',bg='Lavender').grid(row=1,column=3)
            Label(root5,text='Balance',font='times 10 bold',bg='Lavender').grid(row=2,column=3)
            bal=Entry(root5,font='times 10 bold',bd=3)
            bal.insert(0,i[8])
            bal.grid(row=2,column=4)
            Label(root5,text='Pin no',font='times 13',bg='Lavender').grid(row=3,column=3)
            pin=Entry(root5,font='times 10 bold',bd=3)
            pin.insert(0,i[9])
            pin.grid(row=3,column=4)
            Label(root5,text='Nomination',font='times 13',bg='Lavender').grid(row=4,column=3)
            nomi=Entry(root5,font='times 10 bold',bd=3)
            nomi.insert(0,i[10])
            nomi.grid(row=4,column=4)
            Label(root5,text='Card no.',font='times 13',bg='Lavender').grid(row=5,column=3)
            card=Entry(root5,font='times 10 bold',bd=3)
            card.insert(0,i[11])
            card.grid(row=5,column=4)
            Label(root5,text='date of joining',font='times 13',bg='Lavender').grid(row=6,column=3)
            doj=Entry(root5,font='times 10 bold',bd=3)
            doj.insert(0,i[12])
            doj.grid(row=6,column=4)
            Button(root5,text='Back',width=10,height=2,bd=5,command=root5.destroy).grid(row=8,column=5)  
    Button(root2,text='Show',width=10,height=2,bd=5,font='times 10 bold',command=show).grid(row=8,column=3)
    Button(root2,text='Modify',width=10,height=2,bd=5,font='times 10 bold',command=modify).grid(row=8,column=4)
    Button(root2,text='Back',width=10,height=2,bd=5,font='times 10 bold',command=root2.destroy).grid(row=8,column=5)        
Button(root,text='Credit an account',font='times 10 bold',width=20,height=1,bd=5,command=credit).grid(row=2,column=2)
##########################################debit account#############################################################################################################
def debit():
    root3=Tk()
    root3.configure(bg='Lavender')
    root3.title("Bank management system")
    Label(root3,text='Enter account number',font='times 15 bold',bg='Lavender').grid(row=0,column=0)
    l=Entry(root3,font='times 15 bold',bd=3)
    l.grid(row=0,column=1)
    Label(root3,text='Enter amount to be debited',font='times 15 bold',bg='Lavender').grid(row=2,column=0)
    s=Entry(root3,font='times 15 bold',bd=3)
    s.grid(row=2,column=1)
    def modify():
        k=int(l.get())
        cur.execute('select n from detail where detail.l=(?)',(k,))
        x=cur.fetchone()
        x=int(x[0])
        v=int(s.get())
        
        if(v>x):
             showerror('ERROR','debit account is greater than existing balance')
        else:
            y=int(x)-int(s.get())
            cur.execute('UPDATE detail SET n=? WHERE l=?',(y,k))
        con.commit()    
    def show():
        k=l.get()
        cur.execute('select * from detail where detail.l=?',(k,))
        ans=cur.fetchall()
        con.commit()
        for i in ans:
            root6=Tk()
            root6.configure(bg='Lavender')
            root6.title("Bank management system")
            Label(root6,text='Debit cash from account',font='times 20 bold italic',fg='red',bg='Lavender').grid(row=0,column=1)
            Label(root6,text='Consumer Details',font='times 10 bold',relief='ridge',bg='Lavender').grid(row=1,column=1,columnspan=2)
            Label(root6,text='Name',font='times 13',bg='Lavender').grid(row=2,column=1)
            name=Entry(root6,font='times 10 bold',bd=3)
            name.insert(0,i[0])
            name.grid(row=2,column=2)
            Label(root6,text='Father name',font='times 13',bg='Lavender').grid(row=3,column=1)
            fname=Entry(root6,font='times 10 bold',bd=3)
            fname.insert(0,i[1])
            fname.grid(row=3,column=2)
            Label(root6,text='Date of birth',font='times 13',bg='Lavender').grid(row=4,column=1)
            dob=Entry(root6,font='times 10 bold',bd=3)
            dob.insert(0,i[2])
            dob.grid(row=4,column=2)
            Label(root6,text='Address',font='times 13',bg='Lavender').grid(row=5,column=1)
            address=Entry(root6,font='times 10 bold',bd=3)
            address.insert(0,i[3])
            address.grid(row=5,column=2)
            Label(root6,text='Gender',font='times 13',bg='Lavender').grid(row=6,column=1)
            gender=Entry(root6,font='times 10 bold',bd=3)
            gender.insert(0,i[4])
            gender.grid(row=6,column=2)
            Label(root6,text='Mobile number',font='times 13',bg='Lavender').grid(row=7,column=1)
            mobno=Entry(root6,font='times 10 bold',bd=3)
            mobno.insert(0,i[5])
            mobno.grid(row=7,column=2)
            Label(root6,text='Aadhar card',font='times 13',bg='Lavender').grid(row=8,column=1)
            aadhar=Entry(root6,font='times 10 bold',bd=3)
            aadhar.insert(0,i[6])
            aadhar.grid(row=8,column=2)
            Label(root6,text='Enter account number',font='times 13 ',bg='Lavender').grid(row=0,column=3)
            accno=Entry(root6,font='times 10 bold',bd=3)
            accno.insert(0,i[7])
            accno.grid(row=0,column=4)
            Label(root6,text='Account details',font='times 10 bold',bg='Lavender',relief='ridge').grid(row=1,column=3)
            Label(root6,text='Balance',font='times 13',bg='Lavender').grid(row=2,column=3)
            bal=Entry(root6,font='times 10 bold',bd=3)
            bal.insert(0,i[8])
            bal.grid(row=2,column=4)
            Label(root6,text='Pin no',font='times 13',bg='Lavender').grid(row=3,column=3)
            pin=Entry(root6,font='times 10 bold',bd=3)
            pin.insert(0,i[9])
            pin.grid(row=3,column=4)
            Label(root6,text='Nomination',font='times 13',bg='Lavender').grid(row=4,column=3)
            nomi=Entry(root6,font='times 10 bold',bd=3)
            nomi.insert(0,i[10])
            nomi.grid(row=4,column=4)
            Label(root6,text='Card no.',font='times 13',bg='Lavender').grid(row=5,column=3)
            card=Entry(root6,font='times 10 bold',bd=3)
            card.insert(0,i[11])
            card.grid(row=5,column=4)
            Label(root6,text='date of joining',font='times 13',bg='Lavender').grid(row=6,column=3)
            doj=Entry(root6,font='times 10 bold',bd=3)
            doj.insert(0,i[12])
            doj.grid(row=6,column=4)
            Button(root6,text='Back',font='times 10 bold',width=10,height=2,bd=5,command=root6.destroy).grid(row=8,column=5)      
    Button(root3,text='Show',font='times 10 bold',width=10,height=2,bd=5,command=show).grid(row=8,column=3)
    Button(root3,text='Modify',font='times 10 bold',width=10,height=2,bd=5,command=modify).grid(row=8,column=4)
    Button(root3,text='Back',font='times 10 bold',width=10,height=2,bd=5,command=root3.destroy).grid(row=8,column=5)        
Button(root,text='Debit Account',font='times 10 bold',width=20,height=1,bd=5,command=debit).grid(row=3,column=2,pady=10)
Button(root,text='EXIT',font='times 10 bold',width=10,height=2,bd=5,command=root.destroy).grid(row=50,column=3)
#############################################################show account details##############################################
def acc_details():
    root4=Tk()
    root4.configure(bg='Lavender')
    root4.title("Bank management system")
    Label(root4,text='Enter account number',font='times 15 bold',bg='lavender').grid(row=0,column=0)
    l=Entry(root4,font='times 15 bold',bd=3)
    l.grid(row=0,column=1)
    def shows():
        k=l.get()
        cur.execute('select * from detail where detail.l=?',(k,))
        ans=cur.fetchall()
        con.commit()
        for i in ans:
            root7=Tk()
            root7.configure(bg='lavender')
            Label(root7,text='Show Account Details',font='times 20 bold italic',fg='red',bg='lavender').grid(row=0,column=1)
            Label(root7,text='Consumer Details',font='times 10 bold',bg='lavender',relief='ridge').grid(row=1,column=1,columnspan=2)
            Label(root7,text='Name',bg='lavender').grid(row=2,column=1)
            na=Entry(root7,font='times 10 bold',bd=3)
            na.insert(0,i[0])
            na.grid(row=2,column=2)
            Label(root7,text='Father name',font='times 13',bg='lavender').grid(row=3,column=1)
            fna=Entry(root7,font='times 10 bold',bd=3)
            fna.insert(0,i[1])
            fna.grid(row=3,column=2)
            Label(root7,text='Date of birth',font='times 13',bg='lavender').grid(row=4,column=1)
            dobb=Entry(root7,font='times 10 bold',bd=3)
            dobb.insert(0,i[2])
            dobb.grid(row=4,column=2)
            Label(root7,text='Address',font='times 13',bg='lavender').grid(row=5,column=1)
            addr=Entry(root7,font='times 10 bold',bd=3)
            addr.insert(0,i[3])
            addr.grid(row=5,column=2)
            Label(root7,text='Gender',font='times 13',bg='lavender').grid(row=6,column=1)
            gen=Entry(root7,font='times 10 bold',bd=3)
            gen.insert(0,i[4])
            gen.grid(row=6,column=2)
            Label(root7,text='Mobile number',font='times 13',bg='lavender').grid(row=7,column=1)
            mob=Entry(root7,font='times 10 bold',bd=3)
            mob.insert(0,i[5])
            mob.grid(row=7,column=2)
            Label(root7,text='Aadhar card',font='times 13',bg='lavender').grid(row=8,column=1)
            aadh=Entry(root7,font='times 10 bold',bd=3)
            aadh.insert(0,i[6])
            aadh.grid(row=8,column=2)
            Label(root7,text='Enter account number',font='times 13',bg='lavender').grid(row=0,column=3)
            acc=Entry(root7,font='times 10 bold',bd=3)
            acc.insert(0,i[7])
            acc.grid(row=0,column=4)
            Label(root7,text='Account details',font='times 10 bold',relief='ridge').grid(row=1,column=3)
            Label(root7,text='Balance',font='times 13',bg='lavender').grid(row=2,column=3)
            ba=Entry(root7,font='times 10 bold',bd=3)
            ba.insert(0,i[8])
            ba.grid(row=2,column=4)
            Label(root7,text='Pin no',font='times 13',bg='lavender').grid(row=3,column=3)
            pi=Entry(root7,font='times 10 bold',bd=3)
            pi.insert(0,i[9])
            pi.grid(row=3,column=4)
            Label(root7,text='Nomination',font='times 13',bg='lavender').grid(row=4,column=3)
            nom=Entry(root7,font='times 10 bold',bd=3)
            nom.insert(0,i[10])
            nom.grid(row=4,column=4)
            Label(root7,text='Card no.',font='times 13',bg='lavender').grid(row=5,column=3)
            car=Entry(root7,font='times 10 bold',bd=3)
            car.insert(0,i[11])
            car.grid(row=5,column=4)
            Label(root7,text='date of joining',font='times 13',bg='lavender').grid(row=6,column=3)
            dojj=Entry(root7,font='times 10 bold',bd=3)
            dojj.insert(0,i[12])
            dojj.grid(row=6,column=4)   
    Button(root4,text='show',font='times 10 bold',width=10,height=2,bd=5,command=shows).grid(row=8,column=3)
    Button(root4,text='Back',font='times 10 bold',width=10,height=2,bd=5,command=root4.destroy).grid(row=8,column=4)
Button(root,text='Show Account Details',font='times 10 bold',width=20,height=1,bd=5,command=acc_details).grid(row=3,column=0,pady=10)
######################################################delete account####################################################################################################
def delete():
    root5=Tk()
    root5.configure(bg='Lavender')
    root5.title("Bank management System")
    Label(root5,text='Enter account number',font='times 15 bold').grid(row=0,column=0)
    l=Entry(root5,font='times 15 bold',bd=3)
    l.grid(row=0,column=1)
    def dele():
        k=[l.get()]
        cur.execute("DELETE FROM detail WHERE detail.l=(?)",k)
        con.commit()    
        showinfo('OK','Account details deleted successfully')
    Button(root5,text='Delete',font='times 10 bold',width=10,height=2,bd=5,command=dele).grid(row=8,column=4)
Button(root,text='Delete Account',font='times 10 bold',width=20,height=1,bd=5,command=delete).grid(row=4,column=0,pady=10)
root.mainloop()
